INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Ruídos', 'Físicos', 'verde');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Vibrações', 'Físicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Radiações Ionizantes', 'Físicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Radiações não Ionizantes', 'Físicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Frio', 'Físicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Calor', 'Físicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Pressões Anormais', 'Físicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Umidade', 'Físicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Poeiras', 'Químicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Fumos', 'Químicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Névoas', 'Químicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Neblinas', 'Químicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Gases', 'Químicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Vapores', 'Químicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Substâncias, compostos ou produtos químicos em geral', 'Químicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Vírus', 'Biológicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Bactérias', 'Biológicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Protozoários', 'Biológicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Fungos', 'Bilógicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Parasitas', 'Bilógicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Bacilos', 'Biológicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Esforço físico intenso', 'Ergonômicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Levantamento e transporte manual de peso', 'Ergonômicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Exigência de postura inadequada', 'Ergonômicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Controle rígido de produtividade', 'Ergonômicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Imposição de ritmos excessivos', 'Ergonômicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Trabalho em turno e noturno', 'Ergonômicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Jornadas de trabalho prolongadas', 'Ergonômicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Monotonia e repetitividade', 'Ergonômicos');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Outras situações causadas de stress físico e/ou psíquico', 'Ergonômico');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Arranjo físico inadequado', 'Acidentes');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Máquinas e equipamentos sem proteção', 'Acidentes');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Ferramentas inadequadas ou defeituosas', 'Acidentes');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Iluminação inadequada', 'Acidentes');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Eletricidade', 'Acidentes');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Probabilidade de incêndio ou explosão', 'Acidentes');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Armazenamento inadequado', 'Acidentes');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Animais peçonhentos', 'Acidentes');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`) VALUES ('Outras situações de risco que poderão contribuir para a ocorrencia de acidentes', 'Acidentes');
