INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Ruídos', 'Físicos', 'verde', '#29bd04');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Vibrações', 'Físicos', 'verde', '#29bd04');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Radiações Ionizantes', 'Físicos', 'verde', '#29bd04');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Radiações não Ionizantes', 'Físicos', 'verde', '#29bd04');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Frio', 'Físicos', 'verde', '#29bd04');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Calor', 'Físicos', 'verde', '#29bd04');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Pressões Anormais', 'verde', 'Físicos', '#29bd04');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Umidade', 'Físicos', 'verde', '#29bd04');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Poeiras', 'Químicos', 'vermelho', '#d80606');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Fumos', 'Químicos', 'vermelho','#d80606');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Névoas', 'Químicos', 'vermelho','#d80606');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Neblinas', 'Químicos', 'vermelho','#d80606');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Gases', 'Químicos', 'vermelho','#d80606');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Vapores', 'Químicos', 'vermelho','#d80606');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Substâncias, compostos ou produtos químicos em geral', 'Químicos','vermelho', '#d80606');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Vírus', 'Biológicos','marrom', '#ce6108');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Bactérias', 'Biológicos','marrom', '#ce6108');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Protozoários', 'Biológicos','marrom', '#ce6108');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Fungos', 'Bilógicos','marrom', '#ce6108');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Parasitas', 'Bilógicos','marrom', '#ce6108');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Bacilos', 'Biológicos','marrom', '#ce6108');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Esforço físico intenso', 'Ergonômicos','amarelo', '#f1c70a');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Levantamento e transporte manual de peso', 'Ergonômicos','amarelo', '#f1c70a');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Exigência de postura inadequada', 'Ergonômicos','amarelo', '#f1c70a');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Controle rígido de produtividade', 'Ergonômicos','amarelo', '#f1c70a');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Imposição de ritmos excessivos', 'Ergonômicos','amarelo', '#f1c70a');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Trabalho em turno e noturno', 'Ergonômicos','amarelo', '#f1c70a');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Jornadas de trabalho prolongadas', 'Ergonômicos','amarelo', '#f1c70a');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Monotonia e repetitividade', 'Ergonômicos','amarelo', '#f1c70a');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Outras situações causadas de stress físico e/ou psíquico', 'Ergonômico','amarelo', '#f1c70a');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Arranjo físico inadequado', 'Acidentes','azul', '#0751c0');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Máquinas e equipamentos sem proteção', 'Acidentes','azul', '#0751c0');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Ferramentas inadequadas ou defeituosas', 'Acidentes','azul', '#0751c0');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Iluminação inadequada', 'Acidentes','azul', '#0751c0');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Eletricidade', 'Acidentes','azul', '#0751c0');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Probabilidade de incêndio ou explosão', 'Acidentes','azul', '#0751c0');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Armazenamento inadequado', 'Acidentes','azul', '#0751c0');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Animais peçonhentos', 'Acidentes','azul', '#0751c0');
INSERT INTO `jsst`.`agentes_riscos` (`risco`, `tipo`, `cor`, `hexadecimal`) VALUES ('Outras situações de risco que poderão contribuir para a ocorrencia de acidentes', 'Acidentes','azul', '#0751c0');
